parameters:
  loginResponse:
    type: "object"
    properties:
      token:
        type: "string"
  participants:
    type: "object"
    properties:
      characterId:
        type: "string"
        description: "Id персонажа"
      status:
        type: "string"
        enum:
          - "Присутствовал"
          - "Отсутствовал"
          - "Отпросился"
  token:
    name: "token"
    in: "header"
    description: "Токен авторизации"
    required: "true"
    type: "string"
  createCharacter:
    name: "body"
    in: "body"
    required: "true"
    schema:
      $ref: "#/definitions/CharacterDTO"
